### ISSUE TITLE
Session.SessionIdString is obsolete

### ISSUE THREAD

**Issue by ubbeK** [StarcounterPrefabs/GoogleSignIn#9]
Two warnings when building GoogleSignIn:

> C:\GitHub\StarcounterSamples\GoogleSignIn\src\GoogleSignIn\Helpers\SignInOut.cs(12,128,12,159): warning CS0618: 'Session.SessionIdString' is obsolete: 'Please use ToAsciiString() instead.'
> C:\GitHub\StarcounterSamples\GoogleSignIn\src\GoogleSignIn\Helpers\SignInOut.cs(77,43,77,74): warning CS0618: 'Session.SessionIdString' is obsolete: 'Please use ToAsciiString() instead.'

Replace the `SessionIdString` with the `ToAsciiString()` method. These are the same warnings as from the [Simplified issue](https://github.com/StarcounterSamples/Simplified/issues/12)

**Comment by Mackiovello** [comment]
`SessionIdString` is now replaced by `SessionId`. Closing the issue

**Comment by warpech** [comment]
Actually the message says to use `ToAsciiString()`... Which one is it then? 

cc @alemoi

**Comment by Mackiovello** [comment]
@warpech both are deprecated in favor of `SessionId`, see [here](https://github.com/Starcounter/Starcounter/issues/3586)
